# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1plYm1nslqx3FbzgIDFV_BYy6KKfBKNB4
"""

# Remove problematic versions
!pip uninstall -y gensim scipy numpy

# Install versions known to work well together
!pip install numpy==1.23.5
!pip install scipy==1.10.1
!pip install gensim==4.3.1

import gensim
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_json('/content/drive/MyDrive/data/tutrial_tensorflow/review/Cell_Phones_and_Accessories_5.json',lines=True)

df.head()

review_text=df.reviewText.apply(gensim.utils.simple_preprocess)
review_text

model=gensim.models.Word2Vec(
    window=10,
    min_count=2,
    workers=4
)

model.build_vocab(review_text,progress_per=1000)

model.train(review_text,total_examples=model.corpus_count,epochs=model.epochs)

model.wv.most_similar('bad')

model.wv.similarity(w1='good',w2='great')